services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - /var/registry/NetRegistry/Registry.API/Nginx/nginx.conf:/etc/nginx/nginx.conf
#      - /var/registry/NetRegistry/Registry.API/Nginx/dev.samanii.key:/etc/certificate/dev.samanii.key
#      - /var/registry/NetRegistry/Registry.API/Nginx/dev.samanii.cer:/etc/certificate/dev.samanii.cer
    restart: unless-stopped
    networks:
      - nginx-network

  registry.api:
    image: registry.api
    ports:
      - 8080:8080
      - 8081:8081
    build:
      context: .
      dockerfile: Registry.API/Dockerfile
    depends_on:
      - registryDB
      - nginx
#    networks:
#      - nginx-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - registryDB
      - nginx

  registryDB:
    image: postgres
    container_name: postgresDb
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Hossein*(!^
      POSTGRES_DB: registry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - nginx-network

volumes:
  postgres_data:
    
networks:
  nginx-network:
    driver: bridge
