services:
  registry.api:
    image: registry.api
    ports:
      - 8080:8080
      - 8081:8081
    build:
      context: .
      dockerfile: Registry.API/Dockerfile
    depends_on:
      - registryDB
      
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - registryDB

  registryDB:
    image: postgres
    container_name: postgresDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
