name: Auto Cache Busting for Changed Files

on:
  push:
    branches:
      - master

jobs:
  cache-busting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Show Changes
        run: git diff
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          debug: true
          script: |
            cd /var/registry
            git pull
            docker-compose down
            docker-compose build
            docker-compose up -d
